// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0EHsBggd1ZmNEDVWmAd5q0hqrWsQiPnE',
    appId: '1:400512326050:web:a59b5d3e4fbb17013dbafb',
    messagingSenderId: '400512326050',
    projectId: 'chat-app-4bf14',
    authDomain: 'chat-app-4bf14.firebaseapp.com',
    storageBucket: 'chat-app-4bf14.appspot.com',
    measurementId: 'G-54N8RS4N14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3yoSjwnHm1-G9dsswzBBxntw9DXCQA-E',
    appId: '1:400512326050:android:ff7460db75b55c043dbafb',
    messagingSenderId: '400512326050',
    projectId: 'chat-app-4bf14',
    storageBucket: 'chat-app-4bf14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkhU0rL_NZV9_gnASjzIz8_d0iTouBQxY',
    appId: '1:400512326050:ios:426d3ed1f2148b903dbafb',
    messagingSenderId: '400512326050',
    projectId: 'chat-app-4bf14',
    storageBucket: 'chat-app-4bf14.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkhU0rL_NZV9_gnASjzIz8_d0iTouBQxY',
    appId: '1:400512326050:ios:7f062b56eba6d0303dbafb',
    messagingSenderId: '400512326050',
    projectId: 'chat-app-4bf14',
    storageBucket: 'chat-app-4bf14.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
